export const SET_USER = 'SET_USER'
export const AUTH_IS_READY = 'AUTH_IS_READY'
export const FETCH_ITEMS = 'FETCH_ITEMS'
export const SIGN_OUT = 'SIGN_OUT'
export const SET_CART_SHOW = 'SET_CART_SHOW'
export const ADD_TO_CART = 'ADD_TO_CART'
export const FETCH_CART_ITEM = 'FETCH_CART_ITEM'